services:

    mybuilder.cronos_bundle.annotation_cron_exporter:
        class: MyBuilder\Bundle\CronosBundle\Exporter\AnnotationCronExporter
        arguments:
            - '@annotation_reader'
        calls:
            - [ setConfig, [%mybuilder.cronos_bundle.exporter_config%] ]

    mybuilder.cronos_bundle.cron_process_updater:
        class: MyBuilder\Cronos\Updater\CronUpdater
        arguments: [ '@mybuilder.cronos_bundle.cron_manipulator' ]

    mybuilder.cronos_bundle.cron_manipulator:
        class: MyBuilder\Cronos\Updater\CommandCronManipulator
        arguments:
            - '@mybuilder.cronos_bundle.process_runner'
            - '@mybuilder.cronos_bundle.filesystem'
        private: true

    mybuilder.cronos_bundle.process_runner:
        class: MyBuilder\Cronos\Updater\SymfonyProcessRunner
        private: true

    mybuilder.cronos_bundle.filesystem:
        class: MyBuilder\Cronos\Updater\SymfonyFileSystem
        private: true
